avatar task
js-tasks-ru/htmlcss-20220317_alekevge pull request #10
Opened 2022-04-16 20:03 UTC by alekevge

2022-04-16 20:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-16 20:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-16 20:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-17 11:21 UTC, GSemikozov requested changes

2022-04-17 11:21 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    border-radius: 100%;
50%

2022-04-17 11:21 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    height: 100%; /* ставим только height потому  что div - display:block - занимает всю ширину контейнера */
неа, вот здесь как раз будет фиксированная ширина и высота - 102px, - поскольку аватар будет всегда одного размера при ресайзе или изменении размеров экрана

2022-04-18 14:16 UTC, GSemikozov approved these changes

2022-04-18 14:16 UTC, merged